### ISSUE TITLE
日期区间选择的时候报错

### ISSUE THREAD

**Issue by imouren** [ihadoop/metabase-doris-driver#1]
![image](https://github.com/ihadoop/metabase-doris-driver/assets/2245847/8e8f337f-3b45-4693-9f15-673cb4afa109)

**Comment by ihadoop** [comment]
> ![image](https://private-user-images.githubusercontent.com/2245847/312714644-8e8f337f-3b45-4693-9f15-673cb4afa109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDMxMDcsIm5iZiI6MTcxMDQwMjgwNywicGF0aCI6Ii8yMjQ1ODQ3LzMxMjcxNDY0NC04ZThmMzM3Zi0zYjQ1LTQ2OTMtOWYxNS02NzNjYjRhZmExMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMDc1MzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NkMmY4MzZhNTQzMDBlZTU3ZWYxNGQzMmM2YzJjZDE5YjhiYWI3MDZkOTcwNzhjZWI4M2QwYzIwYjQ3NDkzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T76eSqz2RbiP8lq-HM495_vc9YaQqaSCieen_9ab4XY)

i have fixed it. you can unzip this file ，using new jar。 can i add your wechat
[doris.metabase-driver.jar.zip](https://github.com/ihadoop/metabase-doris-driver/files/14598776/doris.metabase-driver.jar.zip)

**Comment by ihadoop** [comment]
https://github.com/ihadoop/metabase-doris-driver/releases/tag/v-0.0.2
